version: '3.3'

services:
  dev:
    container_name: vpn_server
    image: vpn_server:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn run start:prod
    ports:
      - 3000:3980
      - 80:3981
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
